
PETICION_SOLICITAR_BICI = "-1"
PETICION_DEJAR_BICI = "1"

KMS_DEJAR_BICI = 'kilometros_entrada'
KMS_COGER_BICI = 'kilometros_salida'
PETICIONES_NORESUELTAS_COGER_BICI = 'noResueltasEntrada'
PETICIONES_NORESUELTAS_SOLTAR_BICI = 'noResueltasSalida'

PETICIONES_RESUELTAS_COGER_BICI = 'ResueltaEntrada'
PETICIONES_RESUELTAS_SOLTAR_BICI = 'ResueltaSalida'


OCUPACION = 'ocupacion'
OCUPACION_HORAS = 'ocupacionHoras'
OCUPACION_RELATIVA = 'ocupacionRelativa'
OCUPACION_RELATIVA_HORAS = 'ocupacionRelativaHoras'

DESPLAZAMIENTOS = 'desplazamiento'

KMS_COGER_BICI_HORAS = 'kilometros_salida_horas'
KMS_DEJAR_BICI_HORAS = 'kilometros_entrada_horas'

KMS_FICTICIOS_COGER = 'kilometros_ficticios_coger'
KMS_FICTICIOS_DEJAR = 'kilometros_ficticios_dejar'

PETICIONES_NORESUELTAS_FICTICIAS_COGER_BICI = 'NoResuelta_Ficticia_Coger'
PETICIONES_NORESUELTAS_FICTICIAS_DEJAR_BICI = 'NoResuelta_Ficticia_Dejar'


LISTA_MATRICES = [OCUPACION,OCUPACION_RELATIVA,KMS_COGER_BICI,KMS_DEJAR_BICI,PETICIONES_RESUELTAS_COGER_BICI,PETICIONES_RESUELTAS_SOLTAR_BICI,
                  PETICIONES_NORESUELTAS_COGER_BICI,PETICIONES_NORESUELTAS_SOLTAR_BICI,KMS_FICTICIOS_COGER,KMS_FICTICIOS_DEJAR,
                  PETICIONES_NORESUELTAS_FICTICIAS_COGER_BICI,PETICIONES_NORESUELTAS_FICTICIAS_DEJAR_BICI]

DELTA_TIME = 15

MATRIZDESPLAZAMIENTOS_PETICIONES = 4
MATRIZDESPLAZAMIENTOS_UTEMPORAL = 3

CAPACIDAD_MAXIMA_INICIAL = 5068

COORDENADAS = []

COSTE_ANDAR = 3

PORCENTAJE_ESTRES = 0.1